# Generated by Django 5.1.2 on 2024-11-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('reservada', 'Reservada'), ('cancelada', 'Cancelada')], max_length=15),
        ),
    ]
