# Generated by Django 5.1.2 on 2025-06-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_reserva_estado_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaservicio',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='reservaservicio',
            name='servicio_lavanderia',
        ),
        migrations.RemoveField(
            model_name='serviciolavanderia',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='serviciolavanderia',
            name='usuario',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible')], default='disponible', max_length=15),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='ReservaServicio',
        ),
        migrations.DeleteModel(
            name='ServicioLavanderia',
        ),
    ]
