# Generated by Django 5.1.2 on 2025-10-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_factura_pagada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
    ]
